### ISSUE TITLE
error: Error getting IMDB ID:  [503]

### ISSUE THREAD

**Issue by madvtak** [lokenx/plexrequests-meteor#427]
Hi,

i'm sorry if this has been discussed but I tried looking. So i went from a different branch to this one. My other one crashed and i didn't feel like dealing with it anymore and it was already out of date. 

I installed this version in docker and I installed the latest. I was getting an error and saw your warning about Meteor 1.3. So i figured that the latest pull had the new Meteor 1.3. So i went back a release to "46" Same deal, getting Error getting IMDB ID error [503]

So without having to go back 1 release at a time, are you able to tell me which version/release i should download?

This is whats in my log when i try a search. 

`2017-01-06 11:09:36	stdout	error: Error getting IMDB ID: 1701 [503]
2017-01-06 11:09:36	stdout	{ [Error: ETIMEDOUT] stack: [Getter] }`

**Comment by madvtak** [comment]
Okay i tested with Sonarr, and that seemed to pull just fine. I guess its the issue with movie pulls.

**Comment by lokenx** [comment]
Assuming your CouchPotato is up to date, I'd get the latest version of the app 1.15.6 I believe--start there and see what happens. Not sure what branch you were on so not sure what that could have done.

**Comment by madvtak** [comment]
I believe i am on the most current version. 

Version: b538f900 (12/21/2016, 10:25:09AM)

**Comment by cmilam87** [comment]
I am also having the same issue running the latest version 1.15.6

**Comment by naisspas** [comment]
Same issue on latest version 1.15.6 (running in docker). Most searches work, but some movies with accented characters give the error (for exemple the documentary "La vallée des loups") when I click on the "+ Request" button

**Comment by rigrassm** [comment]
Issue was likely resolved in v1.15.7. 

Tested the movie La vallée des loups and was able to get back results.

**Comment by madvtak** [comment]
Scream Failed
![image](https://cloud.githubusercontent.com/assets/18261123/23117023/7a2be9d4-f702-11e6-9ca6-0aaf81f69b79.png)

I downloaded the latest for Linux.IO it still shows 1.15.6
![image](https://cloud.githubusercontent.com/assets/18261123/23117029/8512e47e-f702-11e6-869f-c78b95b01461.png)

**Comment by rigrassm** [comment]
You will need to build the container yourself if you wish to use the
updated version. Otherwise, you'll have to wait until Linuxserver.io team
rebuilds the image unfortunately.

**Comment by madvtak** [comment]
I have turned off the container. Does PlexRequest AutoUpdate in app like Sonarr or NZBHydra?

**Comment by tresni** [comment]
Seeing this issue on 1.20.4, any additional details on what is causing this?  Happening on any movie it seems.

**Comment by lokenx** [comment]
Can list some specific movies you're trying and the search you try for them
as well?
