### ISSUE TITLE
Radarr:  Couldn't submit request, please try again!

### ISSUE THREAD

**Issue by fm-techbts** [lokenx/plexrequests-meteor#484]
Get this error when trying to request a movie through Radarr

I20170802-19:13:43.320(-5)? Radarr Movie Get -> connect ECONNREFUSED
I20170802-19:13:43.320(-5)? Radarr Movie Post -> Match error: Expected string, got undefined
I20170802-19:13:48.482(-5)? Radarr Movie Get -> connect ECONNREFUSED
I20170802-19:13:48.482(-5)? Radarr Movie Post -> Match error: Expected string, got undefined
I20170802-19:13:51.729(-5)? Radarr Movie Get -> connect ECONNREFUSED
I20170802-19:13:51.729(-5)? Radarr Movie Post -> Match error: Expected string, got undefined
I20170802-19:13:54.656(-5)? Radarr Movie Get -> connect ECONNREFUSED
I20170802-19:13:54.656(-5)? Radarr Movie Post -> Match error: Expected string, got undefined

That is whats showing on terminal. I'm on macOS 10.12.6 running the latest release from github.

**Comment by rigrassm** [comment]
Do you have a quality profile set for Radarr?

**Comment by fm-techbts** [comment]
I do and PR was able to load them successfully.

**Comment by Inevitable** [comment]
I too am experiencing this issue.  Docker on CentOS for both Plex Requests and Radarr.

**Comment by Bigluu** [comment]
I'm experiencing the same issue. Using the Docker images provided by Linuxserver (https://github.com/linuxserver) for Radarr and PR.

**Comment by noinip** [comment]
I'm also having this problem. Same as Bigluu. I see the profiles. I tried selecting a few different ones. I even went into Radarr and created a new profile and then selected that in PR. No go.

**Comment by Bungeetaco** [comment]
Same issue. running the linuxserver/plexrequests-meteor image on Ubuntu Server 16.04LTS. Connection test is successful and I can pull the profiles, but adding a new or existing TV shows gives an error message. 
![2017-10-17_16-54-55](https://user-images.githubusercontent.com/5958682/31689028-28370084-b35c-11e7-9a1e-e2577497ca66.gif)

**Comment by rigrassm** [comment]
Looks like you're testing Radarr's connection settings but are trying to
add a TV series. Radarr is for managing movies, Sonarr is for TV series.

**Comment by Bungeetaco** [comment]
Same thing happens when trying to add a movie.

**Comment by jamiehd** [comment]
I'm getting the same issue. It searches fine but won't add the film.

**Comment by Pingblue** [comment]
I had the same issue in both Radarr/Sonarr but after clicking get profiles and selecting one and saving I can now add through Plex requests.

I'm using Linuxserver docker images.

**Comment by rigrassm** [comment]
Yeah, I can't reproduce this issue other than by not having the profile set.

Remember, you have to enter the server info, update the settings, click the
get profiles button and select your profile, then save the settings again.

**Comment by jamiehd** [comment]
I have just resaved the profile to make sure and I'm still getting the error, Is there something that could be preventing that setting from saving? Or is there anything else that could be causing it that you know of?

Thanks

**Comment by rigrassm** [comment]
What error messages are you getting again?

**Comment by rigrassm** [comment]
In the logs/console output that is.

**Comment by jamiehd** [comment]
Sorry I fixed it after I commented and edited my comment. It was caused by me not setting the minimum quality. Thanks very much for your help.

**Comment by rigrassm** [comment]
No problem and thanks for the updates.

**Comment by danieljrich17** [comment]
I'm still having this issue, and I do have the profile and minimum availability set. Test connecting to Radarr server is a success, and all settings have been updated. Anything else that could be causing this issue?

![image](https://user-images.githubusercontent.com/22357358/33563655-c61dfff2-d8d5-11e7-9015-c845d1749a4b.png)

**Comment by PipeItToDevNull** [comment]
This issue is still alive for me, has any proper fix been found?
