### ISSUE TITLE
TV Show request will give an error when it works fine in Sonarr

### ISSUE THREAD

**Issue by ersan** [lokenx/plexrequests-meteor#492]
When submitting a request for a TV Show through plex requests it will say there was an error adding the show, when I look at the log it says "error: Method not found [404]", and when I look at the javascript console its says to check the server log for errors, but it adds to Sonarr perfectly fine and searches for and downloads episodes without issue.

**Comment by fuse-dev** [comment]
I am seeing the same issue with TV Shows. I have just installed it fresh on different computer and still see the issue. So I am not sure if its plexrequests issue or maybe sonarr. (fwiw my sonarr version is 2.0.0.4949)
But it would be useful to be able to know what method it is trying to call. (Not used meteor before so not really sure where to look)

**Comment by chierichetto** [comment]
Seeing the same with TV-shows as well. Using CouchPotato.
Just installed Plex Requests. Movies works great.

**Comment by andrewmeyer** [comment]
+1

**Comment by fuse-dev** [comment]
Think I might have found where the problem is

The tvseasons method is commented out in plexrequests/server/methods/helpers/tv/tvmazeMethods.js

That must be the method that is generating the Method not found [404] error

// tvseasons:function(id){
     //     var seasonSearch = HTTP.get('http://api.tvmaze.com/shows' + '/' + id + '/seasons', {})
     //     return seasonSearch.data
// }

If you uncomment this block it appears to work again.

But I don't know why it was commented out and if there are any other implications of re-enabling it.
I will go and look through the commits to see if there is anything about the change in there

**Comment by andrewmeyer** [comment]
I can confirm that uncommenting the code block fixes the issue.
It looks like the block was commented out in 5d95537  which was a bug fix as well as code standardization.  It also looks like the code was added here: 033bcc7

**Comment by rigrassm** [comment]
@andrewmeyer Thanks for the find, that was actually commented out while I was testing something and somehow slipped through the cracks. I'll be pushing a fix in a bit.

**Comment by rigrassm** [comment]
Fix has been committed and is available in release v1.20.10.

**Comment by fuse-dev** [comment]
Nice, thanks

**Comment by jasii** [comment]
I'm still having this error on 1.20.10 with Sonarr 2.0.0.4949 - Aug 12 2017

**Comment by FirstRulez** [comment]
I think there is an issue with the linuxserver.io docker as it does not seem to want to update PlexRequests. The error I see in the logs is 
`Exception while invoking method 'checkForUpdate' Error: ENOENT, no such file or directory '/app/bundle/version.txt'`
I'm going to post this to their forums to see if anyone there has a fix.

**Comment by rigrassm** [comment]
Can you try spinning up a fresh instance that doesn't have any possible cached data?

Also, could share your permissions requirements for TV shows so that I can try and replicate this issue. I can't seem to get the behavior to manifest using the default permissions nor my own.

**Comment by rigrassm** [comment]
FWIW, I'm running they're containers as well. It may be worth backing up your database and completely remove the container and then pull down the image again to ensure its fresh.

**Comment by alexwitherspoon** [comment]
I can confirm this error: 

> error | Method not found [404] | 2017/10/11 09:17:34
> -- | -- | --

PlexRequests Version v1.20.10
Sonarr version 2.0.0.4949
Both ls.io dockers.

Attempted a fresh install with DB backup and no change of behavior. Looking to test further.

**Comment by rigrassm** [comment]
Can you provide me with your permissions settings/restrictions as well as
the exact steps to replicate?

**Comment by rigrassm** [comment]
My bad, didn't get the last line in the email notification.

@alexwitherspoon - if you are familiar with docker can you try dropping into the container and checking if the last method in the file below is actually uncommented?

`<appdir>/server/methods/helpers/tv/tvmazeMethods.js`

Should be around lines 77-80.

**Comment by alexwitherspoon** [comment]
Standard or Admin user logs into plexrequests, go to request TV show, and gets the below error. See included snapshots just to help provide clarity. Happy to share more as need/do more testing.

https://photos.app.goo.gl/6XCGRoMh6L5CaR9B3

**Comment by alexwitherspoon** [comment]
Ok definitely digging into the ls.io docker container, they have nested this node.js app within a wrapper node.js app... Giving this a look to figure out how they are doing this. (no dockerfile to rely on here, it's all closed source).

**Comment by alexwitherspoon** [comment]
root@ea346f961246:/# cat /app/bundle/programs/server/app/server/methods/helpers/tv/tvmazeMethods.js

> (function(){Meteor.methods({
>     tvmaze:function(search, type){
>         check(search, String)
>         check(type, String)
> 
>         var searchURL = 'http://api.tvmaze.com/search/shows'
> 
>         try {
>             var response = HTTP.get(searchURL, {params: {q: search}})
>             var searchResults = JSON.parse(response.content)
>         }
>         catch (error) {
>             console.log(error)
>             return error.status_message
>         }
> 
>         var results = []
>         for (var i in searchResults) {
> 
>             if (searchResults.hasOwnProperty(i)) {
> 
>                 var s = searchResults[i].show
> 
>                 // Moved the tvdb check to the top, should break immediately if no tvdbID exists.
>                 if (s.externals.thetvdb === null) {
>                     break
>                 }
> 
>                 var tvdb = s.externals.thetvdb
> 
>                 var id = s.id || 0
>                 var title = s.name || name || 'Unknown'
>                 var release_date = s.premiered || 0
>                 var year = (release_date != 0) ? release_date.slice(0, 4) : 0
>                 var overview = s.summary.replace(/<(?:.|\n)*?>/gm, '') || 'No overview.'
>                 overview = (overview.length > 250) ? overview.slice(0, 250) + '...' : overview
>                 var link = s.url || 'https://www.tvmaze.com/' + id + '/' + title
>                 var media_type = type || 'undefined'
>                 var index = i
> 
>                 if (s.image !== null) {
>                     var poster_path = s.image.medium || s.image.original || '/'
>                 }
> 
>                 if (poster_path !== null && poster_path !== undefined) {
>                     var s_poster_path = poster_path.replace('http', 'https')
>                 } else {
>                     s_poster_path = '/'
>                 }
> 
>                 // var seasonSearch = HTTP.get(seasonURL + "/" + id + "/seasons", {});
>                 // var seasonList = seasonSearch.data;
> 
>                 results.push({
>                     'id': id,
>                     'tvdb': tvdb,
>                     'title': title,
>                     'year': year,
>                     'release_date': release_date,
>                     'overview': overview,
>                     'poster_path': s_poster_path,
>                     'link': link,
>                     'media_type': media_type,
>                     'index': index,
>                     'seasons': null
>                 })
>             }
>         }
>         return results
>     },
> 
>     /*
>    New function to get season info for a show, moved this out of the main search function as it
>    didn't need to be called for every search result. This may change when granular season
>    selection gets implemented but either way it should be it's own function call.
>   */
>     // tvseasons:function(id){
>     //     var seasonSearch = HTTP.get('http://api.tvmaze.com/shows' + '/' + id + '/seasons', {})
>     //     return seasonSearch.data
>     // }
> })
> 
> }).call(this);
> 
> //# sourceMappingURL=tvmazeMethods.js.map

**Comment by alexwitherspoon** [comment]
Looks like the linuxserver.io image is somehow still not updated to the right version despite displaying the right version.

**Comment by sparklyballs** [comment]
@alexwitherspoon our image is NOT closed source in any way shape or form

everything is viewable and editable via PR on our github repository

**Comment by FirstRulez** [comment]
Thanks all for looking at this. I can confirm the screenshots and symptoms above exactly match what I am seeing.
Is there an alternate / recommended docker I should or could look to use instead of LS.io?

**Comment by sparklyballs** [comment]
our image is updated once a week on friday evenings at a random time between 11pm and midnight uk time

since the update to plexrequests that addressed this issue was 5 days ago and after our last update our image would not have picked it up yet

manually triggered an update that should be available fairly soon

**Comment by rigrassm** [comment]
@sparklyballz thanks for that information! Been pulling my hair out trying
to figure this one out lol.

In the future, if I have a critical change published should I just open an
issue with y'all's repo requesting a rebuild so users can get the fixes
sooner?

**Comment by rigrassm** [comment]
@alexwitherspoon It looks like the Linuxserver.io guys have rebuilt their docker container. Can you pull down the updated container and test again?

**Comment by ehumps** [comment]
@rigrassm I just pulled the linuxserver.io container and it appears to be working normally again!

**Comment by rigrassm** [comment]
Awesome! Putting this one to bed finally lol. Thanks for everyone's help!
