### ISSUE TITLE
IFTTT Notifications Stopped Working After Updating to v1.20.9

### ISSUE THREAD

**Issue by ohmar** [lokenx/plexrequests-meteor#493]
Hello,

IFTTT notifications stopped working after updating v1.20.9. Here is the error message that shows up when sending a test notification;

"Match error: Expected object, got string".

I believe this is because server/methods/admin/adminMethods.js checks to see if the request sent is an Object when it should be a String.

**Comment by rigrassm** [comment]
See my comment in Pull request #495. The issue will be resolved soon.

**Comment by rigrassm** [comment]
Fixed in [v1.20.11](https://github.com/lokenx/plexrequests-meteor/tree/v1.20.11)

**Comment by jakest** [comment]
I'm still getting this in v1.20.11 when testing IFTTT. It tests fine with curl. Any ideas?

**Comment by rigrassm** [comment]
Have you tried testing from a fresh install? The test function is hard
coded with an object so it can't be sending a string anymore. Meteor
sometimes will cache things and might need to be reset in order to clear it
out. Be sure to backup your database before doing this.
